;this file for FamiTone2 library generated by FamiStudio

.base $E000

untitled_music_data:
	db 1
	dw @instruments
	dw @samples-3
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	db <(@tempo_env16), >(@tempo_env16), 0, 0

@instruments:
	dw @env13,@env0,@env9,@env8
	dw @env12,@env0,@env7,@env8
	dw @env1,@env0,@env10,@env5
	dw @env6,@env0,@env14,@env11
	dw @env4,@env0,@env3,@env2

@samples:
@env0:
	db $c0,$7f,$00,$00
@env1:
	db $00,$ca,$03,$c9,$02,$c8,$02,$c7,$c7,$c6,$c6,$c5,$00,$0b
@env2:
	db $00,$c0,$17,$c1,$c2,$c3,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$c0,$c1,$c2,$c3,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$c0,$00,$03
@env3:
	db $c2,$c0,$c2,$00,$02
@env4:
	db $00,$c9,$c9,$c8,$c8,$c7,$c6,$00,$06
@env5:
	db $00,$c0,$22,$c1,$c2,$c3,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$c0,$00,$03
@env6:
	db $04,$c3,$7f,$00,$01
@env7:
	db $c1,$c2,$c1,$c3,$c1,$00,$04
@env8:
	db $00,$c0,$7f,$00,$01
@env9:
	db $7f,$00,$00
@env10:
	db $c0,$c1,$00,$01
@env11:
	db $00,$c0,$1c,$c1,$c2,$c2,$c1,$c0,$bf,$be,$be,$bf,$c0,$00,$03
@env12:
	db $00,$c3,$c2,$05,$c2,$02,$c2,$00,$04
@env13:
	db $04,$c2,$7f,$00,$01
@env14:
	db $c2,$c1,$c3,$00,$02
@tempo_env16:
	db $01,$09,$05,$04,$04,$05,$04,$04,$05,$80

@song0ch0:
@song0ch0loop:
@ref0:
	db $f7,$f7,$f7,$f7,$f7,$a7
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
@ref1:
	db $bf,$86,$38,$f7,$85,$31,$f7,$85,$33,$f7,$85,$34,$f7,$85,$38,$bd
@ref2:
	db $bf,$31,$f7,$85,$33,$f7,$87,$34,$f7,$83,$39,$f7,$85,$31,$bd
@ref3:
	db $bf,$33,$f7,$85,$34,$f7,$85,$38,$f7,$85,$31,$f7,$85,$33,$bd
@ref4:
	db $bf,$34,$f7,$85,$36,$f7,$85,$31,$f7,$85,$33,$f7,$85,$34,$bd
@ref5:
	db $bf,$38,$f7,$85,$31,$f7,$85,$33,$f7,$85,$34,$f7,$85,$36,$bd
@ref6:
	db $f7,$f7,$ef,$00,$f7,$f7,$ad
	db $fd
	dw @song0ch0loop

@song0ch1:
@song0ch1loop:
	db $ff,$06
	dw @ref0
@ref7:
	db $84,$34,$85,$69,$02,$97,$f9,$f7,$e5,$31,$9d,$f9,$df,$33,$9b,$f9,$f7,$e5
@ref8:
	db $31,$ad,$f9,$8b,$33,$b3,$f9,$89,$34,$9d,$f9,$f7,$a5,$38,$9f,$f9,$bb,$36,$87,$f9,$95,$33,$d9,$f9,$df
@ref9:
	db $2f,$bb,$f9,$bf,$31,$bb,$2f,$34,$db,$31,$33,$9b,$34,$81,$33,$db,$f9,$f7,$a3,$33,$2f,$bd
@ref10:
	db $bd,$33,$31,$f7,$83,$2f,$33,$bb,$31,$34,$bb,$33,$33,$bb,$36,$34,$bb,$33,$36,$f7,$83,$34,$34,$bd
@ref11:
	db $bb,$36,$81,$33,$b9,$34,$81,$31,$bb,$f9,$f7,$f7,$f7,$a9,$00,$ab
	db $ff,$06
	dw @ref0
@ref12:
	db $88,$36,$f7,$85,$31,$f7,$85,$33,$f7,$85,$34,$f7,$85,$38,$f7,$85
@ref13:
	db $31,$f7,$85,$33,$f7,$85,$34,$f7,$85,$36,$f7,$85,$31,$f7,$85
@ref14:
	db $33,$f7,$85,$34,$f7,$85,$38,$f7,$85,$31,$f7,$85,$33,$f7,$85
@ref15:
	db $34,$f7,$85,$36,$f7,$85,$31,$f7,$85,$33,$f7,$85,$34,$f7,$85
@ref16:
	db $38,$f7,$85,$31,$f7,$85,$33,$f7,$85,$34,$f7,$85,$36,$f7,$85
@ref17:
	db $f7,$c9,$00,$f7,$f7,$f7,$d3
	db $fd
	dw @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref18:
	db $7f,$80,$19,$bb,$00,$20,$bb,$00,$28,$db,$f9,$b3,$72,$ab,$19,$bd,$20,$bd,$27,$bd,$f9,$8b,$7d,$8b,$7b,$91,$79,$d3
@ref19:
	db $7f,$19,$bb,$00,$20,$bb,$00,$28,$db,$f9,$b3,$72,$ab,$19,$bd,$20,$bd,$27,$bd,$f9,$8b,$7d,$8b,$7b,$91,$79,$d3
	db $ff,$16
	dw @ref19
@ref20:
	db $81,$21,$bb,$28,$bd,$2f,$f7,$c5,$21,$bd,$28,$bd,$30,$f7,$c5
	db $ff,$0f
	dw @ref20
	db $ff,$16
	dw @ref19
	db $ff,$16
	dw @ref19
@ref21:
	db $19,$bd,$21,$bd,$28,$bd,$2d,$f7,$c5,$21,$bd,$28,$bd,$30,$bd,$2f,$bd
@ref22:
	db $f7,$87,$19,$bd,$21,$bd,$2f,$bd,$2d,$f7,$c5,$21,$bd,$28,$bd
@ref23:
	db $30,$bd,$2f,$f7,$c5,$19,$bd,$21,$bd,$28,$bd,$2d,$f7,$c5
@ref24:
	db $21,$bd,$28,$bd,$30,$bd,$2f,$f7,$c5,$19,$bd,$21,$bd,$28,$bd,$2d,$bd
@ref25:
	db $f7,$87,$21,$bd,$28,$bd,$30,$bd,$2f,$f7,$f7,$cd
	db $ff,$16
	dw @ref19
	db $fd
	dw @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref26:
	db $f7,$f7,$8f,$82,$30,$f7,$f7,$f7,$93,$00
	db $ff,$06
	dw @ref0
@ref27:
	db $30,$f7,$f7,$f7,$f7,$f7,$a1,$00,$81
	db $ff,$06
	dw @ref0
	db $ff,$09
	dw @ref27
	db $ff,$06
	dw @ref0
	db $ff,$09
	dw @ref27
	db $ff,$06
	dw @ref0
	db $ff,$09
	dw @ref27
	db $ff,$06
	dw @ref0
	db $ff,$09
	dw @ref27
	db $ff,$06
	dw @ref0
@ref28:
	db $30,$f7,$f7,$cd,$00,$f7,$f7,$cd
	db $fd
	dw @song0ch3loop

@song0ch4:
@song0ch4loop:
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $ff,$06
	dw @ref0
	db $fd
	dw @song0ch4loop
