;this file for FamiTone2 library generated by FamiStudio

.base $A000

_music_data:
	db 1
	dw @instruments
	dw @samples-3
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,294,245

@instruments:
	dw @env6,@env0,@env4,@env3
	dw @env5,@env0,@env1,@env3
	dw @env2,@env0,@env4,@env3

@samples:
@env0:
	db $c0,$7f,$00,$00
@env1:
	db $c3,$7f,$00,$00
@env2:
	db $04,$cf,$7f,$00,$01
@env3:
	db $00,$c0,$7f,$00,$01
@env4:
	db $7f,$00,$00
@env5:
	db $04,$c8,$7f,$00,$01
@env6:
	db $00,$c6,$03,$c0,$00,$03

@song0ch0:
	db $fb, $03
@song0ch0loop:
@ref0:
	db $82,$2e,$85,$31,$85,$30,$85,$31,$85,$33,$85,$2e,$85,$31,$85,$30,$85
@ref1:
	db $2e,$85,$2c,$85,$33,$85,$2e,$85,$31,$85,$30,$85,$31,$85,$33,$85
@ref2:
	db $2e,$85,$31,$85,$30,$85,$31,$85,$33,$85,$2e,$85,$31,$85,$30,$85
	db $ff,$10
	dw @ref1
	db $fd
	dw @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref3:
	db $82,$3a,$85,$3c,$85,$3d,$85,$3f,$85,$3a,$85,$3c,$85,$41,$85,$3f,$85
@ref4:
	db $3a,$9d,$3d,$9d
@ref5:
	db $3a,$85,$3c,$85,$3d,$85,$3f,$85,$3a,$85,$3c,$85,$41,$85,$3f,$85
@ref6:
	db $3a,$9d,$3d,$9d
	db $fd
	dw @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref7:
	db $84,$2e,$9d,$33,$9d
@ref8:
	db $2e,$9d,$31,$85,$30,$85,$31,$85,$33,$85
@ref9:
	db $2e,$9d,$33,$9d
	db $ff,$0a
	dw @ref8
	db $fd
	dw @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref10:
	db $80,$28,$85,$28,$81,$28,$81,$28,$85,$28,$85,$28,$85,$28,$81,$28,$81,$28,$85,$28,$85
@ref11:
	db $28,$85,$28,$81,$28,$81,$28,$85,$28,$85,$28,$85,$28,$81,$28,$81,$28,$85,$28,$85
	db $ff,$14
	dw @ref11
	db $ff,$14
	dw @ref11
	db $fd
	dw @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref12:
	db $bf
@ref13:
	db $bf
@ref14:
	db $bf
@ref15:
	db $bf
	db $fd
	dw @song0ch4loop

@song0ch5:
@song0ch5loop:
@ref16:
	db $bf
@ref17:
	db $bf
@ref18:
	db $bf
@ref19:
	db $bf
	db $fd
	dw @song0ch5loop

@song0ch6:
@song0ch6loop:
@ref20:
	db $bf
@ref21:
	db $bf
@ref22:
	db $bf
@ref23:
	db $bf
	db $fd
	dw @song0ch6loop
