;this file for FamiTone2 library generated by FamiStudio

.base $A000

_music_data:
	db 1
	dw @instruments
	dw @samples-3
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,360,300

@instruments:
	dw @env7,@env0,@env6,@env5
	dw @env8,@env0,@env6,@env5
	dw @env3,@env0,@env1,@env5
	dw @env4,@env0,@env1,@env5
	dw @env2,@env0,@env6,@env5

@samples:
@env0:
	db $c0,$7f,$00,$00
@env1:
	db $c3,$7f,$00,$00
@env2:
	db $04,$cf,$7f,$00,$01
@env3:
	db $04,$c5,$7f,$00,$01
@env4:
	db $00,$c3,$c5,$c7,$ca,$00,$04
@env5:
	db $00,$c0,$7f,$00,$01
@env6:
	db $7f,$00,$00
@env7:
	db $00,$c6,$03,$c0,$00,$03
@env8:
	db $00,$c6,$05,$c5,$05,$c4,$05,$c3,$06,$c2,$05,$c1,$00,$0b

@song0ch0:
	db $fb, $06
@song0ch0loop:
@ref0:
	db $7f,$00,$dd,$86,$20,$8d,$24,$8d
@ref1:
	db $22,$bd,$00,$a1,$25,$89,$24,$85,$22,$85
@ref2:
	db $20,$81,$22,$81,$20,$8d,$00,$85,$24,$85,$00,$85,$29,$85,$00,$85,$25,$85,$27,$81,$25,$91,$00,$8d,$27,$81,$25,$81,$22,$81,$24,$81
@ref3:
	db $8f,$25,$81,$24,$81,$20,$81,$22,$91,$20,$00,$20,$81,$1f,$81,$22,$85,$20,$99,$00,$9d
@ref4:
	db $20,$00,$20,$00,$20,$00,$20,$00,$20,$83,$00,$20,$00,$20,$8d,$1b,$00,$20,$00,$20,$81,$1f,$81,$1f,$81,$1d,$ad,$1d,$81,$1f,$81,$20,$00,$20,$81
@ref5:
	db $22,$00,$22,$83,$00,$22,$00,$22,$83,$00,$22,$00,$22,$8d,$1b,$81,$1f,$00,$1f,$81,$1d,$00,$1d,$81,$1b,$b5,$24,$85
@ref6:
	db $24,$83,$00,$24,$00,$24,$85,$22,$85,$20,$8b,$00,$20,$81,$27,$00,$27,$81,$25,$81,$27,$81,$25,$8d,$00,$85,$25,$85,$29,$8d,$27,$81,$25,$00,$25,$81,$24,$81
@ref7:
	db $8b,$24,$81,$25,$81,$24,$81,$20,$81,$22,$8d,$20,$00,$20,$00,$20,$81,$1f,$81,$22,$85,$20,$91,$27,$81,$29,$81,$27,$85,$25,$85,$24,$00,$24,$81,$22,$85
	db $ff,$23
	dw @ref4
	db $ff,$1c
	dw @ref5
	db $ff,$26
	dw @ref6
	db $ff,$25
	dw @ref7
	db $ff,$23
	dw @ref4
	db $ff,$1c
	dw @ref5
	db $ff,$26
	dw @ref6
	db $ff,$25
	dw @ref7
	db $ff,$23
	dw @ref4
	db $ff,$1c
	dw @ref5
	db $ff,$26
	dw @ref6
	db $ff,$25
	dw @ref7
@ref8:
	db $00,$bd,$7f,$87,$7e,$87,$7d,$87,$7c,$87,$7b,$20,$85,$7a,$87,$79,$24,$85,$78,$87
@ref9:
	db $77,$22,$85,$76,$87,$75,$87,$74,$87,$73,$87,$72,$87,$71,$87,$70,$87,$00,$a1,$25,$89,$24,$85,$22,$85
	db $fd
	dw @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref10:
	db $7f,$00,$f7,$85
@ref11:
	db $f7,$87
@ref12:
	db $f7,$87
@ref13:
	db $bb,$84,$24,$a1,$00,$9d
@ref14:
	db $24,$8d,$00,$cd,$86,$20,$8d,$24,$8d
@ref15:
	db $22,$9d,$00,$c1,$25,$89,$24,$85,$22,$85
@ref16:
	db $20,$81,$22,$81,$20,$85,$00,$ed
@ref17:
	db $af,$84,$22,$00,$22,$85,$24,$83,$00,$24,$91,$00,$a5
	db $ff,$08
	dw @ref14
	db $ff,$0a
	dw @ref15
	db $ff,$08
	dw @ref16
	db $ff,$0c
	dw @ref17
	db $ff,$08
	dw @ref14
	db $ff,$0a
	dw @ref15
	db $ff,$08
	dw @ref16
	db $ff,$0c
	dw @ref17
	db $ff,$08
	dw @ref14
	db $ff,$0a
	dw @ref15
	db $ff,$08
	dw @ref16
	db $ff,$0c
	dw @ref17
@ref18:
	db $00,$bd,$7f,$87,$7e,$87,$7d,$87,$7c,$87,$7b,$87,$7a,$87,$79,$87,$78,$87
@ref19:
	db $77,$87,$76,$87,$75,$87,$74,$87,$73,$87,$72,$87,$71,$87,$70,$c7
	db $fd
	dw @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref20:
	db $7f,$88,$20,$95,$00,$81,$20,$00,$20,$83,$00,$20,$95,$19,$8d,$00,$89,$19,$00,$19,$83,$00,$19,$83,$00,$19,$00,$19,$00,$19,$85
@ref21:
	db $1b,$8d,$00,$89,$1b,$00,$1b,$83,$00,$1b,$95,$20,$95,$00,$81,$20,$00,$20,$83,$00,$20,$83,$00,$20,$00,$20,$00,$20,$85
@ref22:
	db $20,$95,$00,$81,$20,$00,$20,$83,$00,$20,$85,$00,$8d,$19,$95,$00,$81,$19,$00,$19,$83,$00,$19,$83,$00,$19,$00,$19,$00,$19,$85
@ref23:
	db $20,$95,$00,$81,$1b,$00,$1b,$83,$00,$1b,$95,$20,$95,$00,$81,$20,$00,$20,$83,$00,$20,$83,$00,$20,$00,$20,$00,$20,$85
@ref24:
	db $20,$95,$00,$81,$20,$00,$20,$83,$00,$20,$95,$19,$95,$00,$81,$19,$00,$19,$83,$00,$19,$83,$00,$19,$00,$19,$00,$19,$85
@ref25:
	db $1b,$95,$00,$81,$1b,$00,$1b,$83,$00,$1b,$95,$20,$95,$00,$81,$20,$00,$20,$83,$00,$20,$83,$00,$20,$00,$20,$00,$20,$85
	db $ff,$1d
	dw @ref24
	db $ff,$1d
	dw @ref23
	db $ff,$1d
	dw @ref24
	db $ff,$1d
	dw @ref25
	db $ff,$1d
	dw @ref24
	db $ff,$1d
	dw @ref23
	db $ff,$1d
	dw @ref24
	db $ff,$1d
	dw @ref25
	db $ff,$1d
	dw @ref24
	db $ff,$1d
	dw @ref23
	db $ff,$1d
	dw @ref24
	db $ff,$1d
	dw @ref25
	db $ff,$1d
	dw @ref24
	db $ff,$1d
	dw @ref23
@ref26:
	db $20,$95,$00,$81,$20,$00,$20,$83,$00,$20,$95,$7f,$19,$85,$7e,$87,$7d,$00,$85,$7c,$83,$19,$00,$7b,$19,$83,$00,$7a,$19,$83,$00,$79,$19,$00,$19,$00,$78,$19,$85
@ref27:
	db $1b,$85,$76,$8f,$00,$81,$1b,$00,$1b,$83,$00,$1b,$95,$00,$bd
	db $fd
	dw @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref28:
	db $7f,$8f,$80,$28,$9d,$28,$9d,$28,$9d,$28,$8d
@ref29:
	db $8f,$28,$9d,$28,$9d,$28,$9d,$28,$8d
	db $ff,$09
	dw @ref29
	db $ff,$09
	dw @ref29
@ref30:
	db $82,$27,$8d,$80,$28,$9d,$28,$9d,$28,$9d,$28,$8d
	db $ff,$09
	dw @ref29
	db $ff,$09
	dw @ref29
	db $ff,$09
	dw @ref29
	db $ff,$0a
	dw @ref30
	db $ff,$09
	dw @ref29
	db $ff,$09
	dw @ref29
	db $ff,$09
	dw @ref29
	db $ff,$0a
	dw @ref30
	db $ff,$09
	dw @ref29
	db $ff,$09
	dw @ref29
	db $ff,$09
	dw @ref29
	db $ff,$0a
	dw @ref30
	db $ff,$09
	dw @ref29
	db $ff,$09
	dw @ref29
	db $ff,$09
	dw @ref29
@ref31:
	db $8f,$28,$9d,$28,$8d,$7f,$87,$7e,$87,$7d,$28,$85,$7c,$87,$7b,$87,$7a,$87,$79,$28,$85,$78,$87
@ref32:
	db $77,$87,$76,$87,$75,$28,$85,$74,$87,$73,$87,$72,$87,$71,$28,$85,$70,$97,$28,$9d,$28,$8d
	db $fd
	dw @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref33:
	db $f7,$87
@ref34:
	db $f7,$87
@ref35:
	db $f7,$87
@ref36:
	db $f7,$87
@ref37:
	db $f7,$87
@ref38:
	db $f7,$87
@ref39:
	db $f7,$87
@ref40:
	db $f7,$87
@ref41:
	db $f7,$87
@ref42:
	db $f7,$87
@ref43:
	db $f7,$87
@ref44:
	db $f7,$87
@ref45:
	db $f7,$87
@ref46:
	db $f7,$87
@ref47:
	db $f7,$87
@ref48:
	db $f7,$87
@ref49:
	db $f7,$87
@ref50:
	db $f7,$87
@ref51:
	db $f7,$87
@ref52:
	db $f7,$87
@ref53:
	db $f7,$87
@ref54:
	db $f7,$87
	db $fd
	dw @song0ch4loop

@song0ch5:
@song0ch5loop:
@ref55:
	db $f7,$87
@ref56:
	db $f7,$87
@ref57:
	db $f7,$87
@ref58:
	db $f7,$87
@ref59:
	db $f7,$87
@ref60:
	db $f7,$87
@ref61:
	db $f7,$87
@ref62:
	db $f7,$87
@ref63:
	db $f7,$87
@ref64:
	db $f7,$87
@ref65:
	db $f7,$87
@ref66:
	db $f7,$87
@ref67:
	db $f7,$87
@ref68:
	db $f7,$87
@ref69:
	db $f7,$87
@ref70:
	db $f7,$87
@ref71:
	db $f7,$87
@ref72:
	db $f7,$87
@ref73:
	db $f7,$87
@ref74:
	db $f7,$87
@ref75:
	db $f7,$87
@ref76:
	db $f7,$87
	db $fd
	dw @song0ch5loop

@song0ch6:
@song0ch6loop:
@ref77:
	db $f7,$87
@ref78:
	db $f7,$87
@ref79:
	db $f7,$87
@ref80:
	db $f7,$87
@ref81:
	db $f7,$87
@ref82:
	db $f7,$87
@ref83:
	db $f7,$87
@ref84:
	db $f7,$87
@ref85:
	db $f7,$87
@ref86:
	db $f7,$87
@ref87:
	db $f7,$87
@ref88:
	db $f7,$87
@ref89:
	db $f7,$87
@ref90:
	db $f7,$87
@ref91:
	db $f7,$87
@ref92:
	db $f7,$87
@ref93:
	db $f7,$87
@ref94:
	db $f7,$87
@ref95:
	db $f7,$87
@ref96:
	db $f7,$87
@ref97:
	db $f7,$87
@ref98:
	db $f7,$87
	db $fd
	dw @song0ch6loop
