;this file for FamiTone2 libary generated by FamiStudio

.base $E000

sounds:
	dw @ntsc
	dw @pal
@ntsc:
	dw @sfx_ntsc_money_2
	dw @sfx_ntsc_money_ching
	dw @sfx_ntsc_song_1

@pal:
	dw @sfx_pal_money_2
	dw @sfx_pal_money_ching
	dw @sfx_pal_song_1

@sfx_ntsc_money_2:
	db $82,$00,$81,$6a,$80,$31,$89,$f0,$02,$81,$54,$02,$81,$46,$80,$32
	db $02,$81,$34,$09,$00
@sfx_ntsc_money_ching:
	db $82,$00,$81,$54,$80,$31,$89,$f0,$06,$81,$29,$80,$72,$05,$00
@sfx_ntsc_song_1:
	db $82,$00,$81,$3f,$80,$32,$89,$f0,$02,$81,$29,$05,$00
@sfx_pal_money_2:
	db $82,$00,$81,$62,$80,$31,$89,$f0,$02,$81,$4e,$02,$81,$41,$80,$32
	db $01,$81,$31,$09,$00
@sfx_pal_money_ching:
	db $82,$00,$81,$4e,$80,$31,$89,$f0,$05,$81,$26,$80,$72,$04,$00
@sfx_pal_song_1:
	db $82,$00,$81,$3a,$80,$32,$89,$f0,$02,$81,$26,$04,$00
