;this file for FamiTone2 libary generated by FamiStudio

.base $E000

sounds:
	dw @ntsc
	dw @pal
@ntsc:
	dw @sfx_ntsc_deactivate
	dw @sfx_ntsc_denied
	dw @sfx_ntsc_fish_death
	dw @sfx_ntsc_game_over
	dw @sfx_ntsc_money_purchase
	dw @sfx_ntsc_money_sale
	dw @sfx_ntsc_plant_growth
	dw @sfx_ntsc_selection

@pal:
	dw @sfx_pal_deactivate
	dw @sfx_pal_denied
	dw @sfx_pal_fish_death
	dw @sfx_pal_game_over
	dw @sfx_pal_money_purchase
	dw @sfx_pal_money_sale
	dw @sfx_pal_plant_growth
	dw @sfx_pal_selection

@sfx_ntsc_deactivate:
	db $82,$00,$81,$54,$80,$3f,$89,$f0,$04,$81,$70,$03,$00
@sfx_ntsc_denied:
	db $82,$02,$81,$80,$80,$3f,$89,$f0,$08,$00
@sfx_ntsc_fish_death:
	db $82,$00,$81,$b3,$80,$bf,$89,$f0,$02,$81,$d5,$02,$82,$01,$81,$3f
	db $0b,$00
@sfx_ntsc_game_over:
	db $82,$01,$81,$3f,$80,$3f,$89,$f0,$08,$82,$00,$81,$fd,$08,$81,$d5
	db $08,$81,$9f,$28,$81,$fd,$10,$81,$ef,$18,$82,$01,$81,$2d,$17,$00
@sfx_ntsc_money_purchase:
	db $82,$00,$81,$54,$80,$36,$89,$f0,$06,$81,$29,$80,$7c,$05,$00
@sfx_ntsc_money_sale:
	db $82,$00,$81,$6a,$80,$38,$89,$f0,$02,$81,$54,$80,$3a,$02,$81,$46
	db $80,$3c,$02,$81,$34,$80,$3f,$09,$00
@sfx_ntsc_plant_growth:
	db $82,$00,$81,$d5,$80,$3c,$89,$f0,$02,$81,$a9,$80,$3d,$02,$81,$8e
	db $80,$3e,$02,$81,$6a,$80,$3f,$02,$81,$a9,$80,$78,$02,$81,$8e,$80
	db $76,$02,$81,$6a,$80,$74,$03,$00
@sfx_ntsc_selection:
	db $82,$00,$81,$3f,$80,$3f,$89,$f0,$02,$81,$29,$05,$00
@sfx_pal_deactivate:
	db $82,$00,$81,$4e,$80,$3f,$89,$f0,$04,$81,$68,$02,$00
@sfx_pal_denied:
	db $82,$02,$81,$52,$80,$3f,$89,$f0,$07,$00
@sfx_pal_fish_death:
	db $82,$00,$81,$a6,$80,$bf,$89,$f0,$02,$81,$c6,$02,$82,$01,$81,$29
	db $0a,$00
@sfx_pal_game_over:
	db $82,$01,$81,$29,$80,$3f,$89,$f0,$07,$82,$00,$81,$eb,$07,$81,$c6
	db $06,$81,$94,$22,$81,$eb,$0d,$81,$de,$14,$82,$01,$81,$18,$13,$00
@sfx_pal_money_purchase:
	db $82,$00,$81,$4e,$80,$36,$89,$f0,$05,$81,$26,$80,$7c,$04,$00
@sfx_pal_money_sale:
	db $82,$00,$81,$62,$80,$38,$89,$f0,$02,$81,$4e,$80,$3a,$02,$81,$41
	db $80,$3c,$01,$81,$31,$80,$3f,$09,$00
@sfx_pal_plant_growth:
	db $82,$00,$81,$c6,$80,$3c,$89,$f0,$02,$81,$9d,$80,$3d,$02,$81,$84
	db $80,$3e,$01,$81,$62,$80,$3f,$02,$81,$9d,$80,$78,$02,$81,$84,$80
	db $76,$02,$81,$62,$80,$74,$03,$00
@sfx_pal_selection:
	db $82,$00,$81,$3a,$80,$3f,$89,$f0,$02,$81,$26,$04,$00
