;this file for FamiTone2 library generated by FamiStudio

.base $A000

as_gas_gas_music_data:
	db 1
	dw @instruments
	dw @samples-3
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,245,204

@instruments:
	dw @env6,@env0,@env4,@env3
	dw @env1,@env0,@env4,@env3
	dw @env2,@env0,@env5,@env3

@samples:
@env0:
	db $c0,$7f,$00,$00
@env1:
	db $04,$cf,$7f,$00,$01
@env2:
	db $00,$c4,$c5,$c6,$c5,$c5,$c6,$c8,$c7,$c6,$00,$01
@env3:
	db $00,$c0,$7f,$00,$01
@env4:
	db $7f,$00,$00
@env5:
	db $c1,$7f,$00,$00
@env6:
	db $00,$c6,$05,$c5,$05,$c4,$05,$c3,$06,$c2,$05,$c1,$00,$0b

@song0ch0:
	db $fb, $06
@song0ch0loop:
@ref0:
	db $84,$2e,$ad,$2c,$ad
@ref1:
	db $2e,$ad,$22,$85,$24,$85,$26,$9d
@ref2:
	db $a1
@ref3:
	db $2e,$ad,$2c,$ad
	db $ff,$08
	dw @ref1
@ref4:
	db $a1
@ref5:
	db $2e,$ad,$2c,$ad
	db $ff,$08
	dw @ref1
	db $fd
	dw @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref6:
	db $8f,$84,$32,$ad,$33,$9d
@ref7:
	db $8f,$2b,$bd,$29,$8d
@ref8:
	db $a1
@ref9:
	db $8f,$32,$ad,$33,$9d
	db $ff,$05
	dw @ref7
@ref10:
	db $a1
	db $ff,$05
	dw @ref9
	db $ff,$05
	dw @ref7
	db $fd
	dw @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref11:
	db $00,$dd
@ref12:
	db $df
@ref13:
	db $a1
@ref14:
	db $df
@ref15:
	db $af,$82,$22,$85,$24,$85,$26,$9d
@ref16:
	db $a1
@ref17:
	db $22,$ad,$20,$ad
@ref18:
	db $80,$22,$ad,$22,$85,$24,$85,$26,$9d
	db $fd
	dw @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref19:
	db $00,$dd
@ref20:
	db $df
@ref21:
	db $a1
@ref22:
	db $df
@ref23:
	db $bf,$80,$2b,$00,$87,$2b,$00,$87,$2b,$00,$83
@ref24:
	db $2b,$9f
@ref25:
	db $26,$8d,$2b,$00,$83,$2b,$00,$2b,$00,$87,$2b,$00,$83,$23,$8d,$2b,$00,$83,$2b,$00,$2b,$00,$87,$2b,$00,$83
	db $ff,$1a
	dw @ref25
	db $fd
	dw @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref26:
	db $df
@ref27:
	db $df
@ref28:
	db $a1
@ref29:
	db $df
@ref30:
	db $df
@ref31:
	db $a1
@ref32:
	db $df
@ref33:
	db $df
	db $fd
	dw @song0ch4loop
